// Generated by gencpp from file control/Imu_data.msg
// DO NOT EDIT!


#ifndef CONTROL_MESSAGE_IMU_DATA_H
#define CONTROL_MESSAGE_IMU_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace control
{
template <class ContainerAllocator>
struct Imu_data_
{
  typedef Imu_data_<ContainerAllocator> Type;

  Imu_data_()
    : header()
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , gyro_r(0.0)
    , gyro_p(0.0)
    , gyro_y(0.0)  {
    }
  Imu_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , gyro_r(0.0)
    , gyro_p(0.0)
    , gyro_y(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _acc_x_type;
  _acc_x_type acc_x;

   typedef double _acc_y_type;
  _acc_y_type acc_y;

   typedef double _acc_z_type;
  _acc_z_type acc_z;

   typedef double _gyro_r_type;
  _gyro_r_type gyro_r;

   typedef double _gyro_p_type;
  _gyro_p_type gyro_p;

   typedef double _gyro_y_type;
  _gyro_y_type gyro_y;





  typedef boost::shared_ptr< ::control::Imu_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control::Imu_data_<ContainerAllocator> const> ConstPtr;

}; // struct Imu_data_

typedef ::control::Imu_data_<std::allocator<void> > Imu_data;

typedef boost::shared_ptr< ::control::Imu_data > Imu_dataPtr;
typedef boost::shared_ptr< ::control::Imu_data const> Imu_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control::Imu_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control::Imu_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'control': ['/home/vasista/Desktop/quadrupedal_robot/src/control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control::Imu_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control::Imu_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::Imu_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::Imu_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::Imu_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::Imu_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control::Imu_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e13d478fc5782f061e903f73ff5e15d";
  }

  static const char* value(const ::control::Imu_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e13d478fc5782f0ULL;
  static const uint64_t static_value2 = 0x61e903f73ff5e15dULL;
};

template<class ContainerAllocator>
struct DataType< ::control::Imu_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control/Imu_data";
  }

  static const char* value(const ::control::Imu_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control::Imu_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 acc_x\n\
float64 acc_y\n\
float64 acc_z\n\
float64 gyro_r\n\
float64 gyro_p\n\
float64 gyro_y\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::control::Imu_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control::Imu_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
      stream.next(m.gyro_r);
      stream.next(m.gyro_p);
      stream.next(m.gyro_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Imu_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control::Imu_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control::Imu_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.acc_z);
    s << indent << "gyro_r: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_r);
    s << indent << "gyro_p: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_p);
    s << indent << "gyro_y: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MESSAGE_IMU_DATA_H
