(cl:in-package deeprl-msg)
(cl:export '(HEADER-VAL
          HEADER
          ERROR_DIST-VAL
          ERROR_DIST
          ERROR_ANGLE-VAL
          ERROR_ANGLE
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          DX-VAL
          DX
          DY-VAL
          DY
          DZ-VAL
          DZ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          DROLL-VAL
          DROLL
          DPITCH-VAL
          DPITCH
          DYAW-VAL
          DYAW
          FLJ-VAL
          FLJ
          FLTL-VAL
          FLTL
          FLBL-VAL
          FLBL
          FRJ-VAL
          FRJ
          FRTL-VAL
          FRTL
          FRBL-VAL
          FRBL
          BLJ-VAL
          BLJ
          BLTL-VAL
          BLTL
          BLBL-VAL
          BLBL
          BRJ-VAL
          BRJ
          BRTL-VAL
          BRTL
          BRBL-VAL
          BRBL
          DFLJ-VAL
          DFLJ
          DFLTL-VAL
          DFLTL
          DFLBL-VAL
          DFLBL
          DFRJ-VAL
          DFRJ
          DFRTL-VAL
          DFRTL
          DFRBL-VAL
          DFRBL
          DBLJ-VAL
          DBLJ
          DBLTL-VAL
          DBLTL
          DBLBL-VAL
          DBLBL
          DBRJ-VAL
          DBRJ
          DBRTL-VAL
          DBRTL
          DBRBL-VAL
          DBRBL
))