// Generated by gencpp from file control/Imu_data.msg
// DO NOT EDIT!


#ifndef CONTROL_MESSAGE_IMU_DATA_H
#define CONTROL_MESSAGE_IMU_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control
{
template <class ContainerAllocator>
struct Imu_data_
{
  typedef Imu_data_<ContainerAllocator> Type;

  Imu_data_()
    : acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , gyro_r(0.0)
    , gyro_p(0.0)
    , gyro_y(0.0)  {
    }
  Imu_data_(const ContainerAllocator& _alloc)
    : acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , gyro_r(0.0)
    , gyro_p(0.0)
    , gyro_y(0.0)  {
  (void)_alloc;
    }



   typedef double _acc_x_type;
  _acc_x_type acc_x;

   typedef double _acc_y_type;
  _acc_y_type acc_y;

   typedef double _acc_z_type;
  _acc_z_type acc_z;

   typedef double _gyro_r_type;
  _gyro_r_type gyro_r;

   typedef double _gyro_p_type;
  _gyro_p_type gyro_p;

   typedef double _gyro_y_type;
  _gyro_y_type gyro_y;





  typedef boost::shared_ptr< ::control::Imu_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control::Imu_data_<ContainerAllocator> const> ConstPtr;

}; // struct Imu_data_

typedef ::control::Imu_data_<std::allocator<void> > Imu_data;

typedef boost::shared_ptr< ::control::Imu_data > Imu_dataPtr;
typedef boost::shared_ptr< ::control::Imu_data const> Imu_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control::Imu_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control::Imu_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'control': ['/home/vasista/Desktop/quadrupedal_robot/src/control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control::Imu_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control::Imu_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::Imu_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::Imu_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::Imu_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::Imu_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control::Imu_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a434399257a414fb44320cd9881f0b17";
  }

  static const char* value(const ::control::Imu_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa434399257a414fbULL;
  static const uint64_t static_value2 = 0x44320cd9881f0b17ULL;
};

template<class ContainerAllocator>
struct DataType< ::control::Imu_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control/Imu_data";
  }

  static const char* value(const ::control::Imu_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control::Imu_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 acc_x\n\
float64 acc_y\n\
float64 acc_z\n\
float64 gyro_r\n\
float64 gyro_p\n\
float64 gyro_y\n\
";
  }

  static const char* value(const ::control::Imu_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control::Imu_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
      stream.next(m.gyro_r);
      stream.next(m.gyro_p);
      stream.next(m.gyro_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Imu_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control::Imu_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control::Imu_data_<ContainerAllocator>& v)
  {
    s << indent << "acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.acc_z);
    s << indent << "gyro_r: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_r);
    s << indent << "gyro_p: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_p);
    s << indent << "gyro_y: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MESSAGE_IMU_DATA_H
