# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from control/Imu_data.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Imu_data(genpy.Message):
  _md5sum = "a434399257a414fb44320cd9881f0b17"
  _type = "control/Imu_data"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 acc_x
float64 acc_y
float64 acc_z
float64 gyro_r
float64 gyro_p
float64 gyro_y
"""
  __slots__ = ['acc_x','acc_y','acc_z','gyro_r','gyro_p','gyro_y']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       acc_x,acc_y,acc_z,gyro_r,gyro_p,gyro_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Imu_data, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.acc_x is None:
        self.acc_x = 0.
      if self.acc_y is None:
        self.acc_y = 0.
      if self.acc_z is None:
        self.acc_z = 0.
      if self.gyro_r is None:
        self.gyro_r = 0.
      if self.gyro_p is None:
        self.gyro_p = 0.
      if self.gyro_y is None:
        self.gyro_y = 0.
    else:
      self.acc_x = 0.
      self.acc_y = 0.
      self.acc_z = 0.
      self.gyro_r = 0.
      self.gyro_p = 0.
      self.gyro_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.acc_x, _x.acc_y, _x.acc_z, _x.gyro_r, _x.gyro_p, _x.gyro_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.acc_x, _x.acc_y, _x.acc_z, _x.gyro_r, _x.gyro_p, _x.gyro_y,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.acc_x, _x.acc_y, _x.acc_z, _x.gyro_r, _x.gyro_p, _x.gyro_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.acc_x, _x.acc_y, _x.acc_z, _x.gyro_r, _x.gyro_p, _x.gyro_y,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
